return {
  "EdenEast/nightfox.nvim",
  enable = true,
  opts = function()
    local bluloco = {
      -- syntax
      attribute = "#FF936A",
      bg = "#282C34",
      bgFloat = "#21242D",
      comment = "#636D83",
      constant = "#9F7EFE",
      cursor = "#FFCC00",
      fg = "#ABB2BF",
      keyword = "#10B1FE",
      label = "#50acae",
      method = "#3FC56B",
      module = "#FF839B",
      number = "#FF78F8",
      parameter = "#8bcdef",
      property = "#CE9887",
      punctuation = "#7A82DA",
      string = "#F9C859",
      tag = "#3691FF",
      type = "#FF6480",
      -- workspace
      added = "#177F55",
      changed = "#1B6E9B",
      copilot = "#95A922",
      deleted = "#A14D5B",
      diffAdd = "#105B3D",
      diffChange = "#10415B",
      diffDelete = "#522E34",
      diffText = "#10415B",
      error = "#ff2e3f",
      errorBG = "#FDCFD1",
      hint = "#7982DA",
      info = "#3691ff",
      infoBG = "#D4E3FA",
      mergeCurrent = "#4B3D3F",
      mergeCurrentLabel = "#604B47",
      mergeIncoming = "#2F476B",
      mergeIncomingLabel = "#305C95",
      mergeParent = "#EB1C20",
      mergeParentLabel = "#EB1D29",
      primary = "#3691ff",
      search = "#1A7247",
      selection = "#274670",
      warning = "#da7a43",
      warningBG = "#F2DBCF",

      -- terminal
      rainbowBlue = "#44A5FF",
      rainbowCyan = "#28e4eb",
      rainbowGreen = "#92f535",
      rainbowIndigo = "#9F7EFE",
      rainbowOrange = "#ffa023",
      rainbowRed = "#FF6666",
      rainbowViolet = "#ff78ff",
      rainbowYellow = "#f4ff78",
      terminalBlack = "#42444d",
      terminalBlue = "#3375fe",
      terminalBrightBlack = "#8f9aae",
      terminalBrightBlue = "#10b0fe",
      terminalBrightCyan = "#5fb9bc",
      terminalBrightGreen = "#3fc56a",
      terminalBrightMagenta = "#ff78f8",
      terminalBrightRed = "#ff637f",
      terminalBrightWhite = "#ffffff",
      terminalBrightYellow = "#f9c858",
      terminalCyan = "#4483aa",
      terminalGreen = "#25a45c",
      terminalMagenta = "#9f7efe",
      terminalRed = "#fc2e51",
      terminalWhite = "#cdd3e0",
      terminalYellow = "#ff9369",
      -- Additional colors
      green = "#008200",
      grey10 = "#434753",
      grey20 = "#545864",
      grey25 = "#5A5E6A",
      grey3 = "#2D3037",
      grey30 = "#60646F",
      grey40 = "#6C707B",
      grey5 = "#32363F",
      grey7 = "#393D47",
      shade10 = "#393D47",
      shade2 = "#2A2E37",
      shade25 = "#4A4E58",
      shade30 = "#4F535D",
      shade40 = "#5A5E69",
      shade5 = "#2F333C",
      shade50 = "#646870",
      shade60 = "#6E727C",
      shade7 = "#343841",
      shade70 = "#787C86",
      shade80 = "#828690",
      shade90 = "#8C909A",
      white = "#FFFFFF",
    }

    require("nightfox").setup({
      options = {
        -- Compiled file's destination location
        compile_path = vim.fn.stdpath("cache") .. "/nightfox",
        compile_file_suffix = "_compiled", -- Compiled file suffix
        transparent = false, -- Disable setting background
        terminal_colors = true, -- Set terminal colors (vim.g.terminal_color_*) used in `:terminal`
        dim_inactive = false, -- Non focused panes set to alternative background
        module_default = true, -- Default enable value for modules
        styles = { -- Style to be applied to different syntax groups
          comments = "NONE", -- Value is any valid attr-list value `:help attr-list`
          conditionals = "NONE",
          constants = "NONE",
          functions = "italic",
          keywords = "italic",
          numbers = "italic",
          operators = "NONE",
          strings = "NONE",
          types = "NONE",
          variables = "NONE",
        },
        inverse = { -- Inverse highlight for different types
          match_paren = false,
          visual = false,
          search = false,
        },
        modules = { -- List of various plugins and additional options
          -- ...
        },
      },
      palettes = {
        nordfox = {

          black = bluloco.terminalBlack,
          red = bluloco.type,
          green = bluloco.method,
          yellow = bluloco.string,
          blue = bluloco.keyword,
          magenta = bluloco.constant,
          cyan = bluloco.label,
          white = bluloco.fg,
          orange = bluloco.attribute,
          pink = bluloco.number,
          comment = bluloco.comment,
          bg0 = bluloco.bgFloat,
          bg1 = bluloco.bg,
          bg2 = bluloco.selection,
          bg3 = bluloco.primary,
          bg4 = bluloco.punctuation,
          fg0 = bluloco.parameter,
          fg1 = bluloco.fg,
          fg2 = bluloco.comment,
          fg3 = bluloco.comment,
          sel0 = bluloco.selection,
          sel1 = bluloco.primary,
        },
      },
      specs = {
        nordfox = {
          syntax = {
            operator = bluloco.punctuation,
            field = bluloco.property,
            builtin0 = bluloco.keyword,
            builtin1 = bluloco.keyword,
            builtin2 = bluloco.keyword,
            builtin3 = bluloco.keyword,
            conditional = bluloco.keyword,
            const = bluloco.constant,
            dep = bluloco.comment,
            func = bluloco.method,
            ident = bluloco.fg,
            keyword = bluloco.keyword,
            number = bluloco.number,
            preproc = bluloco.keyword,
            regex = bluloco.string,
            statement = bluloco.keyword,
            string = bluloco.string,
            type = bluloco.type,
            variable = bluloco.fg,
          },
        },
      },
      groups = {
        nordfox = {
          -- Position the name in the word and execute `:Inspect` to get the
          -- correct name from treesitter
          -- ["@namespace"] = { fg = bluloco.type },
          ["@comment.document"] = { fg = bluloco.diffAdd }, -- dark green for docstrings
          ["@spell.phpdoc"] = { fg = bluloco.added }, -- dark green for docstrings
          -- Basic highlights
          Normal = { fg = bluloco.fg, bg = bluloco.bg },
          CursorLine = { bg = bluloco.grey7 },
          CursorColumn = { bg = bluloco.grey7 },
          Whitespace = { fg = bluloco.grey10 },
          Comment = { fg = bluloco.comment },
          LineNr = { fg = bluloco.comment },
          CursorLineNr = { fg = bluloco.comment },
          Search = { bg = bluloco.search },
          IncSearch = { bg = bluloco.cursor, fg = bluloco.bg },
          CurSearch = { bg = bluloco.cursor, fg = bluloco.bg },
          NormalFloat = { bg = bluloco.bgFloat },
          FloatBorder = { fg = bluloco.punctuation },
          NormalSB = { bg = bluloco.bgFloat },
          ColorColumn = { bg = bluloco.grey5 },
          Cursor = { bg = bluloco.cursor, fg = bluloco.bg },
          Directory = { fg = bluloco.keyword },
          Added = { fg = bluloco.method },
          Changed = { fg = bluloco.tag },
          Removed = { fg = bluloco.type },
          DiffAdd = { bg = bluloco.diffAdd },
          DiffChange = { bg = bluloco.diffChange },
          DiffDelete = { bg = bluloco.diffDelete },
          DiffText = { bg = bluloco.diffText },
          EndOfBuffer = { fg = bluloco.punctuation },
          ErrorMsg = { fg = bluloco.error },
          VertSplit = { fg = bluloco.grey30 },
          Winseparator = { fg = bluloco.grey30 },
          Folded = { bg = bluloco.shade7, fg = bluloco.tag },
          SignColumn = { bg = bluloco.bg },
          FoldColumn = { bg = bluloco.bg },
          Substitute = { bg = bluloco.cursor, fg = bluloco.bg },
          MatchParen = { bg = bluloco.punctuation, fg = bluloco.bg },
          ModeMsg = { fg = bluloco.fg },
          MsgArea = { fg = bluloco.fg },
          MoreMsg = { fg = bluloco.primary },
          NonText = { fg = bluloco.shade30 },
          NormalNC = { fg = bluloco.fg, bg = bluloco.bg },
          Pmenu = { bg = bluloco.bgFloat },
          PmenuSel = { bg = bluloco.selection },
          PmenuSbar = { bg = bluloco.grey5 },
          PmenuThumb = { bg = bluloco.punctuation },
          Question = { fg = bluloco.primary },
          QuickFixLine = { bg = bluloco.primary, fg = bluloco.white },
          SpecialKey = { fg = bluloco.attribute },
          StatusLine = { bg = bluloco.grey10 },
          StatusLineNC = { bg = bluloco.shade5 },
          TabLine = { bg = bluloco.shade3, fg = bluloco.shade30 },
          TabLineFill = { bg = bluloco.bg },
          TabLineSel = { bg = bluloco.shade10, fg = bluloco.primary },
          File = { fg = bluloco.primary },
          Title = { fg = bluloco.primary },
          Visual = { bg = bluloco.selection },
          VisualNOS = { bg = bluloco.selection },
          WarningMsg = { fg = bluloco.warning },
          WildMenu = { bg = bluloco.selection },
          Constant = { fg = bluloco.constant },
          String = { fg = bluloco.string },
          Character = { fg = bluloco.attribute },
          Number = { fg = bluloco.number },
          Boolean = { fg = bluloco.keyword },
          Identifier = { fg = bluloco.fg },
          Function = { fg = bluloco.method },
          Method = { fg = bluloco.method },
          Property = { fg = bluloco.property },
          Field = { fg = bluloco.property },
          Parameter = { fg = bluloco.parameter },
          Statement = { fg = bluloco.keyword },
          Punctuation = { fg = bluloco.punctuation },
          Operator = { fg = bluloco.punctuation },
          Keyword = { fg = bluloco.keyword },
          PreProc = { fg = bluloco.keyword },
          Type = { fg = bluloco.type },
          Struct = { fg = bluloco.type },
          Class = { fg = bluloco.type },
          Special = { fg = bluloco.attribute },
          Attribute = { fg = bluloco.attribute },
          Tag = { fg = bluloco.tag },
          Underlined = { gui = "underline" },
          Bold = { gui = "bold" },
          Italic = { gui = "italic" },
          Ignore = { fg = bluloco.bg },
          Error = { fg = bluloco.error },
          Todo = { bg = bluloco.info, fg = bluloco.white },
          WinBar = { fg = bluloco.tag, gui = "bold" },
          WinBarNC = { fg = bluloco.fg },
          -- LSP and diagnostics
          DiagnosticError = { fg = bluloco.error },
          DiagnosticWarn = { fg = bluloco.warning },
          DiagnosticInfo = { fg = bluloco.info },
          DiagnosticHint = { fg = bluloco.hint },
          DiagnosticVirtualTextError = { fg = bluloco.error, bg = bluloco.bgFloat },
          DiagnosticVirtualTextWarn = { fg = bluloco.warning, bg = bluloco.bgFloat },
          DiagnosticVirtualTextInfo = { fg = bluloco.info, bg = bluloco.bgFloat },
          DiagnosticVirtualTextHint = { fg = bluloco.hint, bg = bluloco.bgFloat },
          DiagnosticUnderlineError = { gui = "undercurl", sp = bluloco.error },
          DiagnosticUnderlineWarn = { gui = "undercurl", sp = bluloco.warning },
          DiagnosticUnderlineInfo = { gui = "undercurl", sp = bluloco.info },
          DiagnosticUnderlineHint = { gui = "undercurl", sp = bluloco.hint },
          -- Treesitter
          ["@constructor"] = { fg = bluloco.type },
          ["@operator"] = { fg = bluloco.punctuation },
          ["@punctuation"] = { fg = bluloco.punctuation },
          ["@punctuation.bracket"] = { fg = bluloco.punctuation },
          ["@punctuation.delimiter"] = { fg = bluloco.punctuation },
          ["@punctuation.special"] = { fg = bluloco.punctuation },
          ["@symbol"] = { fg = bluloco.constant },
          ["@constant"] = { fg = bluloco.constant },
          ["@constant.builtin"] = { fg = bluloco.keyword },
          ["@comment"] = { fg = bluloco.comment },
          ["@string.escape"] = { fg = bluloco.attribute },
          ["@method"] = { fg = bluloco.method },
          ["@function"] = { fg = bluloco.method },
          ["@function.call"] = { fg = bluloco.method },
          ["@function.builtin"] = { fg = bluloco.method },
          -- ["@parameter"] = { fg = bluloco.parameter },
          ["@variable.parameter"] = { fg = bluloco.fg },
          ["@field"] = { fg = bluloco.property },
          ["@property"] = { fg = bluloco.property },
          ["@label"] = { fg = bluloco.label },
          ["@type"] = { fg = bluloco.type },
          ["@type.phpdoc"] = { fg = bluloco.label },
          ["@type.builtin"] = { fg = bluloco.keyword },
          ["@type.qualifier"] = { fg = bluloco.keyword },
          ["@keyword"] = { fg = bluloco.keyword },
          ["@keyword.modifier"] = { fg = bluloco.keyword },
          ["@string"] = { fg = bluloco.string },
          ["@namespace"] = { fg = bluloco.module },
          ["@number"] = { fg = bluloco.number },
          ["@annotation"] = { fg = bluloco.label },
          ["@tag.attribute"] = { fg = bluloco.attribute },
          ["@error"] = { fg = bluloco.error },
          ["@warning"] = { fg = bluloco.warning },
          ["@info"] = { fg = bluloco.info },
          ["@text"] = { fg = bluloco.fg },
          ["@text.strong"] = { gui = "bold" },
          ["@text.italic"] = { gui = "italic" },
          ["@text.underline"] = { gui = "underline" },
          ["@text.title"] = { fg = bluloco.keyword },
          ["@text.literal"] = { fg = bluloco.property },
          ["@text.uri"] = { fg = bluloco.tag, gui = "underline" },
          -- Markdown
          ["@markup.heading"] = { fg = bluloco.keyword, gui = "bold" },
          ["@markup.heading.1"] = { fg = bluloco.keyword, gui = "bold" },
          ["@markup.heading.2"] = { fg = bluloco.label, gui = "bold" },
          ["@markup.heading.3"] = { fg = bluloco.method, gui = "bold" },
          ["@markup.heading.4"] = { fg = bluloco.string, gui = "bold" },
          ["@markup.heading.5"] = { fg = bluloco.constant, gui = "bold" },
          ["@markup.heading.6"] = { fg = bluloco.tag, gui = "bold" },
          ["@markup.link"] = { fg = bluloco.tag, gui = "underline" },
          ["@markup.link.label"] = { fg = bluloco.string },
          ["@markup.link.url"] = { fg = bluloco.tag, gui = "underline" },
          ["@markup.code"] = { bg = bluloco.grey5, fg = bluloco.fg },
          ["@markup.raw"] = { fg = bluloco.property },
          ["@markup.raw.block"] = { bg = bluloco.grey5 },
          ["@markup.raw.delimiter"] = { fg = bluloco.comment },
          ["@markup.list"] = { fg = bluloco.punctuation },
          ["@markup.list.checked"] = { fg = bluloco.method },
          ["@markup.list.unchecked"] = { fg = bluloco.fg },
          ["@markup.quote"] = { fg = bluloco.comment, gui = "italic" },
          ["@markup.strong"] = { gui = "bold" },
          ["@markup.italic"] = { gui = "italic" },
          ["@markup.strikethrough"] = { gui = "strikethrough" },
          ["@variable"] = { fg = bluloco.fg },
          ["@variable.constant"] = { fg = bluloco.constant },
          ["@variable.builtin"] = { fg = bluloco.keyword },
          ["@tag"] = { fg = bluloco.tag },
          ["@tag.builtin"] = { fg = bluloco.tag },
          ["@attribute"] = { fg = bluloco.label },
          -- Language specific
          ["@label.json"] = { fg = bluloco.property },
          ["@label.jsonc"] = { fg = bluloco.property },
          ["@label.help"] = { fg = bluloco.tag, gui = "underline" },
          ["@text.uri.html"] = { gui = "underline" },
          -- LSP semantic
          ["@lsp.type.comment"] = { fg = bluloco.comment },
          ["@lsp.type.namespace"] = { fg = bluloco.module },
          ["@lsp.type.type"] = { fg = bluloco.type },
          ["@lsp.type.typeParameter"] = { fg = bluloco.type },
          ["@lsp.type.class"] = { fg = bluloco.type },
          ["@lsp.type.enum"] = { fg = bluloco.type },
          ["@lsp.type.interface"] = { fg = bluloco.type },
          ["@lsp.type.struct"] = { fg = bluloco.type },
          ["@lsp.type.parameter"] = { fg = bluloco.parameter },
          ["@lsp.type.variable"] = { fg = bluloco.fg },
          ["@lsp.type.property"] = { fg = bluloco.property },
          ["@lsp.type.enumMember"] = { fg = bluloco.constant },
          ["@lsp.type.function"] = { fg = bluloco.method },
          ["@lsp.type.method"] = { fg = bluloco.method },
          ["@lsp.type.label"] = { fg = bluloco.label },
          ["@lsp.type.macro"] = { fg = bluloco.label },
          ["@lsp.type.decorator"] = { fg = bluloco.label },
          ["@lsp.type.string"] = { fg = bluloco.string },
          ["@lsp.type.regexp"] = { fg = bluloco.string },
          ["@lsp.type.keyword"] = { fg = bluloco.keyword },
          ["@lsp.type.number"] = { fg = bluloco.number },
          ["@lsp.type.operator"] = { fg = bluloco.punctuation },
          ["@lsp.type.event"] = { fg = bluloco.parameter },
          ["@lsp.mod.readonly"] = { fg = bluloco.constant },
          ["@lsp.mod.constant"] = { fg = bluloco.constant },
          ["@lsp.typemod.variable.constant"] = { fg = bluloco.constant },
          ["@lsp.typemod.function.declaration"] = { fg = bluloco.method },
          ["@lsp.typemod.function.readonly"] = { fg = bluloco.method },
          LspInlayHint = { bg = bluloco.shade2, fg = bluloco.shade25 },
          -- Git signs
          GitSignsAdd = { fg = bluloco.added },
          GitSignsChange = { fg = bluloco.changed },
          GitSignsDelete = { fg = bluloco.deleted },
          GitSignsUntracked = { fg = bluloco.added },
          GitSignsUntrackedNr = { fg = bluloco.added },
          GitSignsUntrackedCul = { fg = bluloco.added },
          GitSignsStagedAdd = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedAddNr = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedAddCul = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedUntracked = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedUntrackedNr = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedUntrackedCul = { bg = bluloco.added, fg = bluloco.bg },
          GitSignsStagedDelete = { bg = bluloco.deleted, fg = bluloco.bg },
          GitSignsStagedDeleteNr = { bg = bluloco.deleted, fg = bluloco.bg },
          GitSignsStagedDeleteCul = { bg = bluloco.deleted, fg = bluloco.bg },
          GitSignsStagedChange = { bg = bluloco.changed, fg = bluloco.bg },
          GitSignsStagedChangeNr = { bg = bluloco.changed, fg = bluloco.bg },
          GitSignsStagedChangeCul = { bg = bluloco.changed, fg = bluloco.bg },
          -- Telescope
          TelescopeNormal = { bg = bluloco.bgFloat },
          TelescopeBorder = { fg = bluloco.punctuation },
          TelescopeTitle = { fg = bluloco.punctuation },
          TelescopeMatching = { fg = bluloco.keyword },
          TelescopePromptPrefix = { fg = bluloco.punctuation },
          TelescopeSelection = { bg = bluloco.selection },
          TelescopeMultiSelection = { fg = bluloco.attribute },
          TelescopeMultiIcon = { fg = bluloco.primary },
          TelescopeResultsClass = { fg = bluloco.type },
          TelescopeResultsField = { fg = bluloco.property },
          TelescopeResultsVariable = { fg = bluloco.fg },
          TelescopeResultsSpecialComment = { fg = bluloco.comment },
          TelescopePreviewLink = { fg = bluloco.label },
          TelescopePreviewSocket = { fg = bluloco.property },
          TelescopePreviewWrite = { fg = bluloco.type },
          TelescopePreviewExecute = { fg = bluloco.method },
          TelescopePreviewSize = { fg = bluloco.number },
          TelescopePreviewUser = { fg = bluloco.property },
          TelescopePreviewGroup = { fg = bluloco.property },
          TelescopePreviewDate = { fg = bluloco.string },
          -- Fzf-lua
          FzfLuaNormal = { bg = bluloco.bgFloat },
          FzfLuaBorder = { fg = bluloco.punctuation },
          FzfLuaTitle = { fg = bluloco.punctuation },
          FzfLuaCursorLine = { bg = bluloco.selection },
          FzfLuaCursorLineNr = { bg = bluloco.selection },
          FzfLuaMatch = { fg = bluloco.keyword },
          FzfLuaPrompt = { fg = bluloco.punctuation },
          FzfLuaPathColNr = { fg = bluloco.number },
          FzfLuaPathLineNr = { fg = bluloco.number },
          FzfLuaBufName = { fg = bluloco.fg },
          FzfLuaBufNr = { fg = bluloco.number },
          FzfLuaBufFlagCur = { fg = bluloco.keyword },
          FzfLuaBufFlagAlt = { fg = bluloco.tag },
          FzfLuaTabTitle = { fg = bluloco.parameter },
          FzfLuaTabMarker = { fg = bluloco.keyword },
          FzfLuaFilePart = { fg = bluloco.fg },
          FzfLuaLiveSym = { fg = bluloco.keyword },
          -- Nvim Tree
          NvimTreeNormal = { bg = bluloco.bgFloat },
          NvimTreeNormalNC = { bg = bluloco.bgFloat },
          NvimTreeWindowPicker = { fg = bluloco.fg, bg = bluloco.selection },
          NvimTreeIndentMarker = { fg = bluloco.punctuation },
          NvimTreeRootFolder = { fg = bluloco.tag },
          NvimTreeFolderIcon = { fg = bluloco.keyword },
          NvimTreeFolderName = { fg = bluloco.tag },
          NvimTreeOpenedFolderName = { fg = bluloco.keyword },
          NvimTreeSpecialFile = { fg = bluloco.constant },
          NvimTreeExecFile = { fg = bluloco.method },
          NvimTreeGitStaged = { fg = bluloco.method },
          NvimTreeGitDirty = { fg = bluloco.type },
          NvimTreeGitMerge = { fg = bluloco.number },
          NvimTreeGitDeleted = { fg = bluloco.deleted },
          NvimTreeGitNew = { fg = bluloco.method },
          -- Snacks
          SnacksNotifierBorderError = { fg = bluloco.error },
          SnacksNotifierBorderWarn = { fg = bluloco.warning },
          SnacksNotifierBorderInfo = { fg = bluloco.info },
          SnacksNotifierBorderDebug = { fg = bluloco.punctuation },
          SnacksNotifierBorderTrace = { fg = bluloco.property },
          SnacksNotifierIconError = { fg = bluloco.error },
          SnacksNotifierIconWarn = { fg = bluloco.warning },
          SnacksNotifierIconInfo = { fg = bluloco.info },
          SnacksNotifierIconDebug = { fg = bluloco.punctuation },
          SnacksNotifierIconTrace = { fg = bluloco.property },
          SnacksNotifierTitleError = { fg = bluloco.error },
          SnacksNotifierTitleWarn = { fg = bluloco.warning },
          SnacksNotifierTitleInfo = { fg = bluloco.info },
          SnacksNotifierTitleDebug = { fg = bluloco.punctuation },
          SnacksNotifierTitleTrace = { fg = bluloco.property },
          SnacksPickerInput = { bg = bluloco.bgFloat },
          SnacksPickerBorder = { fg = bluloco.punctuation },
          SnacksPickerTitle = { fg = bluloco.punctuation },
          SnacksPickerSelected = { fg = bluloco.primary },
          SnacksPickerSearch = { bg = bluloco.selection },
          SnacksPickerMatch = { fg = bluloco.keyword },
          SnacksPickerPrompt = { fg = bluloco.punctuation },
          SnacksPickerCol = { fg = bluloco.number },
          SnacksPickerRow = { fg = bluloco.number },
          SnacksPickerFile = { fg = bluloco.fg },
          SnacksPickerDir = { fg = bluloco.comment },
          SnacksPickerBufFlags = { fg = bluloco.primary },
          SnacksPickerGitStatusAdded = { fg = bluloco.method },
          SnacksPickerGitStatusModified = { fg = bluloco.keyword },
          SnacksPickerGitStatusRenamed = { fg = bluloco.keyword },
          SnacksPickerGitStatusCopied = { fg = bluloco.keyword },
          SnacksPickerGitStatusUnmerged = { fg = bluloco.number },
          SnacksPickerGitStatusDeleted = { fg = bluloco.type },
          SnacksPickerGitStatusIgnored = { fg = bluloco.comment },
          SnacksPickerGitStatusUntracked = { fg = bluloco.attribute },
          SnacksIndent = { fg = bluloco.grey10 },
          SnacksIndentScope = { fg = bluloco.comment },
          SnacksIndent1 = { fg = bluloco.rainbowRed },
          SnacksIndent2 = { fg = bluloco.rainbowYellow },
          SnacksIndent3 = { fg = bluloco.rainbowBlue },
          SnacksIndent4 = { fg = bluloco.rainbowOrange },
          SnacksIndent5 = { fg = bluloco.rainbowGreen },
          SnacksIndent6 = { fg = bluloco.rainbowViolet },
          SnacksIndent7 = { fg = bluloco.rainbowCyan },
          SnacksIndent8 = { fg = bluloco.rainbowIndigo },
          -- Rainbow delimiters
          RainbowDelimiterRed = { fg = bluloco.rainbowRed },
          RainbowDelimiterYellow = { fg = bluloco.rainbowYellow },
          RainbowDelimiterBlue = { fg = bluloco.rainbowBlue },
          RainbowDelimiterOrange = { fg = bluloco.rainbowOrange },
          RainbowDelimiterGreen = { fg = bluloco.rainbowGreen },
          RainbowDelimiterViolet = { fg = bluloco.rainbowViolet },
          RainbowDelimiterCyan = { fg = bluloco.rainbowCyan },
          -- Mason
          -- MasonNormal = { bg = bluloco.bgFloat },
          -- MasonBorder = { fg = bluloco.punctuation },
          -- MasonTitle = { fg = bluloco.punctuation },
          -- MasonHeading = { fg = bluloco.keyword },
          -- MasonMuted = { fg = bluloco.comment },
          -- MasonError = { fg = bluloco.error },
          -- MasonWarning = { fg = bluloco.warning },
          -- MasonSuccess = { fg = bluloco.method },
          -- MasonHighlight = { fg = bluloco.keyword },
          -- MasonHighlightBlock = { bg = bluloco.selection },
          -- MasonHighlightBlockBold = { bg = bluloco.selection, gui = "bold" },
          -- MasonHeader = { fg = bluloco.primary },
          -- MasonMutedBlock = { bg = bluloco.grey5, fg = bluloco.comment },
          -- MasonLink = { fg = bluloco.tag, gui = "underline" },
          -- Copilot
          CopilotSuggestion = { fg = bluloco.copilot },
          CopilotAnnotation = { fg = bluloco.copilot },
          -- Leap
          LeapMatch = { fg = bluloco.keyword, gui = "underline", sp = bluloco.keyword },
          LeapLabel = { bg = bluloco.keyword, fg = bluloco.bg },
          LeapBackdrop = { fg = bluloco.shade40 },
          FlashMatch = { fg = bluloco.keyword, gui = "underline", sp = bluloco.keyword },
          FlashLabel = { bg = bluloco.keyword, fg = bluloco.bg },
          FlashBackdrop = { fg = bluloco.shade40 },
        },
      },
    })

    -- setup must be called before loading
    vim.cmd("colorscheme nordfox")
  end,
}
